@startuml
start

:上传图片(从本机选择或临时拍摄);
:选择标定板;
if (标定板类型?) then (平板)
  :设定标定板规格以及每格大小;
else (圆形版)
  :设定标定板规格以及每格大小;
endif

:获取角点信息,为上传的图片绘制xy轴、原点;
if (是否展示生成结果给用户?) then (是)
  :展示生成的xy轴、原点;
else (否)
endif

if (是否为鱼眼相机?) then (是)
  :设计鱼眼选项;
else (否)
endif

:执行相机标定;
if (是否导出相机参数?) then (是)
  :导出相机参数;
else (否)
endif

stop
@enduml
